:sparkles: Fetch filtered data via dates and keywords
sattiyans/rapidaily pull request #3
Opened 2023-08-21 06:32 UTC by qryskalyst20

2023-08-24 04:29 UTC, Zyten requested changes

2023-08-24 04:29 UTC, Zyten commented on package.json
> +    "rettiwt-api": "^2.0.3"
If not mistaken, you're also using the rettiwt-auth package.

"rettiwt-auth": "^1.2.0"

2023-08-24 04:29 UTC, Zyten commented on scraper.js
> +          endDate: new Date("Tue Aug 22 01:26:23 +0000 2023"), //endDate +1
I suspect eventually, we'd want this to be configurable. But for starters lets make it pull tweets from the last 24 hours like so:

```
startDate: new Date(Date.now() - 86400000),
endDate: new Date(),
```

2023-08-24 04:45 UTC, qryskalyst20 commented on package.json
> +    "rettiwt-api": "^2.0.3"
oh yea i installed it globally i forgot, my bad

2023-08-25 06:25 UTC, Zyten approved these changes
Looks good to me - fixes #2

2023-08-25 06:28 UTC, merged